import type { Perfil, Reputacion } from "@/lib/arkiv/types"

export const PERFILES_MOCK: Perfil[] = [
  {
    perfilId: "perfil-001",
    nombre: "María Gómez",
    foto: "https://i.pravatar.cc/300?img=47",
    rol: "Científica de Datos",
    area: "Data Science",
    bio: "Modelos de visión por computadora y NLP aplicados a industria.",
    verificado: true,
    hitos: [
      { id: "h1", texto: "Charla sobre ML en meetup SaltaDev" },
      { id: "h2", texto: "Lideró modelo de detección de fraude en producción" },
    ],
  },
  {
    perfilId: "perfil-002",
    nombre: "Juan Pérez",
    foto: "https://i.pravatar.cc/300?img=12",
    rol: "Backend Developer",
    area: "Backend",
    bio: "Go y sistemas distribuidos. Fan de la simplicidad y el rendimiento.",
    verificado: true,
    hitos: [
      { id: "h3", texto: "Migró el sistema monolítico a microservicios" },
      { id: "h4", texto: "Armó la infraestructura de CI/CD del equipo" },
    ],
  },
  {
    perfilId: "perfil-003",
    nombre: "Ana Torres",
    foto: "https://i.pravatar.cc/300?img=5",
    rol: "Frontend Developer",
    area: "Frontend",
    bio: "Apasionada por la accesibilidad y las interfaces que la gente entiende de verdad.",
    verificado: true,
    hitos: [
      { id: "h5", texto: "Diseñó el sistema de design tokens del producto" },
      { id: "h6", texto: "Lideró migración a React 18 con cero downtime" },
      { id: "h7", texto: "Llevó la app a cumplimiento WCAG 2.1 AA" },
    ],
  },
  {
    perfilId: "perfil-004",
    nombre: "Carlos Ruiz",
    foto: "https://i.pravatar.cc/300?img=15",
    rol: "DevOps / SRE",
    area: "DevOps",
    bio: "Infraestructura como código, Kubernetes y obsesión con el uptime.",
    verificado: false,
    hitos: [
      { id: "h8", texto: "Migró toda la infra a Kubernetes en 3 meses" },
      { id: "h9", texto: "Mantuvo 99.95% de uptime durante 18 meses" },
      { id: "h10", texto: "Redujo costos AWS un 40% con right-sizing" },
    ],
  },
  {
    perfilId: "perfil-005",
    nombre: "Lucía Méndez",
    foto: "https://i.pravatar.cc/300?img=25",
    rol: "Mobile Developer",
    area: "Mobile",
    bio: "React Native para iOS y Android. Obsesionada con la performance en dispositivos bajos.",
    verificado: true,
    hitos: [
      { id: "h11", texto: "Publicó app con más de 10k descargas activas" },
      { id: "h12", texto: "Implementó offline-first con SQLite y sincronización" },
      { id: "h13", texto: "Redujo tamaño del bundle un 35%" },
    ],
  },
  {
    perfilId: "perfil-006",
    nombre: "Diego Fernández",
    foto: "https://i.pravatar.cc/300?img=33",
    rol: "UX Designer",
    area: "Diseño",
    bio: "Diseño centrado en personas. Figma, investigación de usuarios y sistemas de diseño.",
    verificado: true,
    hitos: [
      { id: "h14", texto: "Rediseñó onboarding, +23% en conversión" },
      { id: "h15", texto: "Armó el sistema de componentes Figma para todo el equipo" },
    ],
  },
  {
    perfilId: "perfil-007",
    nombre: "Valentina Silva",
    foto: "https://i.pravatar.cc/300?img=9",
    rol: "QA Engineer",
    area: "QA",
    bio: "Testing automatizado, calidad desde el primer sprint y cultura de prevención de bugs.",
    verificado: false,
    hitos: [
      { id: "h16", texto: "Automatizó suite de 400 tests E2E con Playwright" },
      { id: "h17", texto: "Implementó testing de performance con k6 en CI" },
    ],
  },
  {
    perfilId: "perfil-008",
    nombre: "Martín López",
    foto: "https://i.pravatar.cc/300?img=18",
    rol: "Backend Developer",
    area: "Backend",
    bio: "Junior aprendiendo en el camino. Node.js y bases de datos relacionales.",
    verificado: false,
    hitos: [
      { id: "h18", texto: "Integró API de pagos con MercadoPago" },
      { id: "h19", texto: "Construyó el módulo de autenticación con JWT" },
    ],
  },
  {
    perfilId: "perfil-009",
    nombre: "Sofía Herrera",
    foto: "https://i.pravatar.cc/300?img=44",
    rol: "Data Scientist",
    area: "Data Science",
    bio: "NLP, MLOps y papers. Prefiere hablar con datos antes que con opiniones.",
    verificado: true,
    hitos: [
      { id: "h20", texto: "Modelo de NLP para clasificación de documentos legales" },
      { id: "h21", texto: "Pipeline de MLOps con reentrenamiento automático en producción" },
      { id: "h22", texto: "Paper aceptado en LatAm AI Conference 2024" },
    ],
  },
  {
    perfilId: "perfil-010",
    nombre: "Nicolás Castro",
    foto: "https://i.pravatar.cc/300?img=52",
    rol: "Frontend Developer",
    area: "Frontend",
    bio: "Arquitectura frontend, performance y micro-frontends. TypeScript estricto.",
    verificado: true,
    hitos: [
      { id: "h23", texto: "Arquitectura micro-frontend con Module Federation" },
      { id: "h24", texto: "Optimizó Core Web Vitals: LCP menor a 1.2s en producción" },
    ],
  },
  {
    perfilId: "perfil-011",
    nombre: "Camila Romero",
    foto: "https://i.pravatar.cc/300?img=38",
    rol: "DevOps Engineer",
    area: "DevOps",
    bio: "GitOps, ArgoCD y mucha paciencia para explicarle a los devs cómo funciona el pipeline.",
    verificado: true,
    hitos: [
      { id: "h25", texto: "Implementó GitOps completo con ArgoCD en 5 equipos" },
      { id: "h26", texto: "Capacitó a 3 equipos en prácticas de CI/CD desde cero" },
    ],
  },
  {
    perfilId: "perfil-012",
    nombre: "Rodrigo Gutiérrez",
    foto: "https://i.pravatar.cc/300?img=60",
    rol: "iOS Developer",
    area: "Mobile",
    bio: "Swift y SwiftUI. Apps de salud y fitness con integración de sensores y ML en device.",
    verificado: false,
    hitos: [
      { id: "h27", texto: "App de salud con más de 50k usuarios activos" },
      { id: "h28", texto: "Integró HealthKit y CoreML en producción" },
      { id: "h29", texto: "Lideró equipo de 4 devs mobile durante 2 años" },
    ],
  },
]

export const REPUTACIONES_MOCK: Record<string, Reputacion> = {
  "perfil-001": {
    perfilId: "perfil-001",
    estrellasBlandas: 4.2,
    estrellasTecnicas: 4.7,
    detalleBlandas: [
      { item: "comunicacion", promedio: 4.5 },
      { item: "colaboracion", promedio: 4.0 },
      { item: "participacion", promedio: 5.0 },
      { item: "ayuda", promedio: 3.5 },
      { item: "liderazgo", promedio: 4.0 },
    ],
    detalleTecnicas: [
      { hitoId: "h1", promedio: 4.5 },
      { hitoId: "h2", promedio: 4.8 },
    ],
  },
  "perfil-002": {
    perfilId: "perfil-002",
    estrellasBlandas: 4.8,
    estrellasTecnicas: 3.5,
    detalleBlandas: [
      { item: "comunicacion", promedio: 5.0 },
      { item: "colaboracion", promedio: 4.8 },
      { item: "participacion", promedio: 4.5 },
      { item: "ayuda", promedio: 5.0 },
      { item: "liderazgo", promedio: 4.7 },
    ],
    detalleTecnicas: [
      { hitoId: "h3", promedio: 3.5 },
      { hitoId: "h4", promedio: 3.5 },
    ],
  },
  "perfil-003": {
    perfilId: "perfil-003",
    estrellasBlandas: 4.7,
    estrellasTecnicas: 2.4,
    detalleBlandas: [
      { item: "comunicacion", promedio: 4.8 },
      { item: "colaboracion", promedio: 5.0 },
      { item: "participacion", promedio: 4.5 },
      { item: "ayuda", promedio: 4.8 },
      { item: "liderazgo", promedio: 4.5 },
    ],
    detalleTecnicas: [
      { hitoId: "h5", promedio: 2.5 },
      { hitoId: "h6", promedio: 2.0 },
      { hitoId: "h7", promedio: 2.8 },
    ],
  },
  "perfil-004": {
    perfilId: "perfil-004",
    estrellasBlandas: 2.2,
    estrellasTecnicas: 4.8,
    detalleBlandas: [
      { item: "comunicacion", promedio: 2.0 },
      { item: "colaboracion", promedio: 2.5 },
      { item: "participacion", promedio: 2.0 },
      { item: "ayuda", promedio: 2.5 },
      { item: "liderazgo", promedio: 2.0 },
    ],
    detalleTecnicas: [
      { hitoId: "h8", promedio: 5.0 },
      { hitoId: "h9", promedio: 4.8 },
      { hitoId: "h10", promedio: 4.5 },
    ],
  },
  "perfil-005": {
    perfilId: "perfil-005",
    estrellasBlandas: 4.3,
    estrellasTecnicas: 4.3,
    detalleBlandas: [
      { item: "comunicacion", promedio: 4.5 },
      { item: "colaboracion", promedio: 4.0 },
      { item: "participacion", promedio: 4.5 },
      { item: "ayuda", promedio: 4.0 },
      { item: "liderazgo", promedio: 4.5 },
    ],
    detalleTecnicas: [
      { hitoId: "h11", promedio: 4.5 },
      { hitoId: "h12", promedio: 4.0 },
      { hitoId: "h13", promedio: 4.5 },
    ],
  },
  "perfil-006": {
    perfilId: "perfil-006",
    estrellasBlandas: 4.9,
    estrellasTecnicas: 2.7,
    detalleBlandas: [
      { item: "comunicacion", promedio: 5.0 },
      { item: "colaboracion", promedio: 4.8 },
      { item: "participacion", promedio: 5.0 },
      { item: "ayuda", promedio: 4.8 },
      { item: "liderazgo", promedio: 5.0 },
    ],
    detalleTecnicas: [
      { hitoId: "h14", promedio: 2.5 },
      { hitoId: "h15", promedio: 2.8 },
    ],
  },
  "perfil-007": {
    perfilId: "perfil-007",
    estrellasBlandas: 3.6,
    estrellasTecnicas: 3.8,
    detalleBlandas: [
      { item: "comunicacion", promedio: 3.5 },
      { item: "colaboracion", promedio: 4.0 },
      { item: "participacion", promedio: 3.5 },
      { item: "ayuda", promedio: 3.5 },
      { item: "liderazgo", promedio: 3.5 },
    ],
    detalleTecnicas: [
      { hitoId: "h16", promedio: 4.0 },
      { hitoId: "h17", promedio: 3.5 },
    ],
  },
  "perfil-008": {
    perfilId: "perfil-008",
    estrellasBlandas: 2.3,
    estrellasTecnicas: 2.5,
    detalleBlandas: [
      { item: "comunicacion", promedio: 2.5 },
      { item: "colaboracion", promedio: 2.5 },
      { item: "participacion", promedio: 2.0 },
      { item: "ayuda", promedio: 2.5 },
      { item: "liderazgo", promedio: 2.0 },
    ],
    detalleTecnicas: [
      { hitoId: "h18", promedio: 2.5 },
      { hitoId: "h19", promedio: 2.5 },
    ],
  },
  "perfil-009": {
    perfilId: "perfil-009",
    estrellasBlandas: 3.1,
    estrellasTecnicas: 4.9,
    detalleBlandas: [
      { item: "comunicacion", promedio: 3.0 },
      { item: "colaboracion", promedio: 3.0 },
      { item: "participacion", promedio: 3.5 },
      { item: "ayuda", promedio: 3.0 },
      { item: "liderazgo", promedio: 3.0 },
    ],
    detalleTecnicas: [
      { hitoId: "h20", promedio: 5.0 },
      { hitoId: "h21", promedio: 4.8 },
      { hitoId: "h22", promedio: 5.0 },
    ],
  },
  "perfil-010": {
    perfilId: "perfil-010",
    estrellasBlandas: 3.7,
    estrellasTecnicas: 4.5,
    detalleBlandas: [
      { item: "comunicacion", promedio: 3.5 },
      { item: "colaboracion", promedio: 4.0 },
      { item: "participacion", promedio: 3.5 },
      { item: "ayuda", promedio: 3.5 },
      { item: "liderazgo", promedio: 4.0 },
    ],
    detalleTecnicas: [
      { hitoId: "h23", promedio: 4.5 },
      { hitoId: "h24", promedio: 4.5 },
    ],
  },
  "perfil-011": {
    perfilId: "perfil-011",
    estrellasBlandas: 4.6,
    estrellasTecnicas: 3.5,
    detalleBlandas: [
      { item: "comunicacion", promedio: 4.5 },
      { item: "colaboracion", promedio: 4.8 },
      { item: "participacion", promedio: 4.5 },
      { item: "ayuda", promedio: 4.5 },
      { item: "liderazgo", promedio: 4.8 },
    ],
    detalleTecnicas: [
      { hitoId: "h25", promedio: 3.5 },
      { hitoId: "h26", promedio: 3.5 },
    ],
  },
  "perfil-012": {
    perfilId: "perfil-012",
    estrellasBlandas: 4.0,
    estrellasTecnicas: 4.2,
    detalleBlandas: [
      { item: "comunicacion", promedio: 4.0 },
      { item: "colaboracion", promedio: 4.0 },
      { item: "participacion", promedio: 4.0 },
      { item: "ayuda", promedio: 4.0 },
      { item: "liderazgo", promedio: 4.0 },
    ],
    detalleTecnicas: [
      { hitoId: "h27", promedio: 4.0 },
      { hitoId: "h28", promedio: 4.5 },
      { hitoId: "h29", promedio: 4.0 },
    ],
  },
}

export const LABEL_ITEM_BLANDO: Record<string, string> = {
  comunicacion: "Comunicación",
  colaboracion: "Colaboración",
  participacion: "Participación",
  ayuda: "Ayuda",
  liderazgo: "Liderazgo",
}
